lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, validate_npm, delete_friend, friend_list, get_friend_list, friend_information

urlpatterns = [
		url(r'^$', index, name='index'),
        url(r'^add-friend/$', add_friend, name='add-friend'),
        url(r'^validate-npm/$', validate_npm, name='validate-npm'),
        url(r'^friend-list/$', friend_list, name='friend-list'),
        url(r'^get-friend-list/$', get_friend_list, name='get-friend-list'),
        url(r'^friend-list/delete-friend/(?P<friend_id>[0-9]+)/$', delete_friend, name='delete-friend'),
        url(r'^friend-list/info/(?P<friend_id>[0-9]+)/$', friend_information, name='info'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10
from lab_1.views import index as index_lab1
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-2-addon/', include (lab_2_addon, namespace='lab-2-addon')),
    url(r'^lab-3/', include(lab_3,namespace='lab-3')),
    url(r'^lab-4/', include(lab_4,namespace='lab-4')),
    url(r'^lab-5/', include(lab_5,namespace='lab-5')),
    url(r'^lab-6/', include(lab_6,namespace='lab-6')),
    url(r'^lab-7/', include(lab_7,namespace='lab-7')),
    url(r'^lab-8/', include(lab_8,namespace='lab-8')),
    url(r'^lab-9/', include(lab_9,namespace='lab-9')),
    url(r'^lab-10/', include(lab_10,namespace='lab-10')),
    url(r'^$', RedirectView.as_view(permanent=True, url='/lab-10/'))
]

lab_7/models.py
from django.db import models

class Friend(models.Model):
    friend_name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250)
    address = models.CharField(max_length=400, default=" ")
    postcode = models.CharField(max_length=100, default=" ")
    hometown = models.CharField(max_length=250, default=" ")
    birthday = models.CharField(max_length=250, default=" ")
    course = models.CharField(max_length=250, default=" ")
    batch = models.CharField(max_length=250, default=" ")
    added_at = models.DateField(auto_now_add=True)

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
import os
import json

response = {}
csui_helper = CSUIhelper()

def index(request):
    # Page halaman menampilkan list mahasiswa yang ada
    # TODO berikan akses token dari backend dengan menggunakaan helper yang ada

    mahasiswa_list = csui_helper.instance.get_mahasiswa_list()
    friend_list = Friend.objects.all()
    auth = csui_helper.instance.get_auth_param_dict()

    page = request.GET.get('page', 1)
    paginate_data = paginate_page(page, mahasiswa_list)
    mahasiswa = paginate_data['data']
    page_range = paginate_data['page_range']

    response = {"mahasiswa_list": mahasiswa, "friend_list": friend_list,"page_range": page_range, "auth": auth}
    html = 'lab_7/lab_7.html'
    return render(request, html, response)


def paginate_page(page, data_list):
    paginator = Paginator(data_list, 10)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    # Get the index of the current page
    index = data.number - 1
    # This value is maximum index of your pages, so the last page - 1
    max_index = len(paginator.page_range)
    # You want a range of 10, so lets calculate where to slice the list
    start_index = index if index >= 10 else 0
    end_index = 10 if index < max_index - 10 else max_index
    # Get our new page range. In the latest versions of Django page_range returns
    # an iterator. Thus pass it to list, to make our slice possible again.
    page_range = list(paginator.page_range)[start_index:end_index]
    paginate_data = {'data':data, 'page_range':page_range}
    return paginate_data

def friend_list(request):
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    html = 'lab_7/daftar_teman.html'
    return render(request, html, response)

def get_friend_list(request):
    if request.method == 'GET':
        friend_list = Friend.objects.all()
        data = serializers.serialize('json', friend_list)
        return HttpResponse(data)

@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']
        address = request.POST['address']
        postcode = request.POST['postcode']
        hometown = request.POST['hometown']
        birthday = request.POST['birthday']
        course = request.POST['course']
        batch = request.POST['batch']
        taken = Friend.objects.filter(npm = npm).exists()
        if(not taken):
            friend = Friend(friend_name=name, npm=npm, address=address, postcode=postcode, hometown=hometown, birthday=birthday, course=course, batch=batch)
            friend.save()
        data = model_to_dict(friend)
        return HttpResponse(data)

def friend_information(request, friend_id):
    friend = Friend.objects.filter(id=friend_id)[0]
    response['friend'] = friend
    html = 'lab_7/info.html'
    return render(request, html, response)

def delete_friend(request, friend_id):
    Friend.objects.filter(id=friend_id).delete()
    return HttpResponseRedirect('/lab-7/friend-list')

@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    data = {
         'is_taken': Friend.objects.filter(npm = npm).exists()
    }
    return JsonResponse(data)

def model_to_dict(obj):
    data = serializers.serialize('json', [obj,])
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <section name="friend-list" id="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2> friend Fasilkom</h2>
                    <div id="friend-list" class="list-group">

                    </div>
                    <form id="add-friend" action="#">
                        {% csrf_token %}
                        <label for="field_npm">npm</label>
                        <input id="field_npm" type="text" name="npm" class="form-control"/>
                        <button type="submit">Tambah</button>
                    </form>

                </div>
            </div>
        </div>
    </section>


{% endblock %}
{% block javascript %}
    <script>
        $( document ).ready(function () {
            $.ajax({
                method: "GET",
                url: '{% url "lab-7:get-friend-list" %}',
                success: function (friend_list) {
                    var friends = JSON.parse(friend_list);
                    if(friends.length == 0){

                        var html = '<div class="alert alert-danger text-center">\
                                <strong>Opps!</strong> Tidak ada mahasiswa \
                            </div>';
                        $("#friend-list").append(html)
                    }else{
                        var counter = 0;
                        $.each(friends,function(index,friend){
                            var button = '<span class="pull-right">'+
                                            '<button type="button" class="btn btn-xs btn-danger"'+
                                            'onClick="deleteFriend('+friend.pk+')">'+
                                                '&times;'+
                                            '</button>'+
                                         '</span>';
                            var info = '<span class="col-xs-2 col-md-1 pull-right">'+
                                            '<button type="button" class="btn btn-xs btn-default btn-block"'+
                                            'onClick="description('+friend.pk+')">'+
                                                'info'+
                                            '</button>'+
                                         '</span>';

                            var html;

                            if(counter % 2 == 0){
                                html = '<a class="list-group-item list-group-item-warning text-center">'+
                                            friend.fields.friend_name +
                                            ' (' + friend.fields.npm + ')' + button + info + '</a>';
                            }else if(counter % 2 == 1){
                                html = '<a class="list-group-item list-group-item-info text-center">'+
                                            friend.fields.friend_name +
                                            ' (' + friend.fields.npm + ')' + button + info + '</a>';
                            }

                            $("#friend-list").append(html)

                            counter += 1;
                        })
                    }
                },
                error: function(error){
                    alert("Terjadi kesalahan");
                }
            });
        });

        function deleteFriend(id){
            event.preventDefault();
            window.open('delete-friend/'+id+'/', '_self');
        }

        function description(id){
            window.open('info/'+id+'/', '_self');
        }
    </script>


    <script>

        var token = document.getElementById("token").innerHTML;
        var cid = document.getElementById("cid").innerHTML;
        alert("tanggal");

        var addFriend = function(npm) {

            $.ajax({
                method: "POST",
                url: '{% url "lab-7:add-friend" %}',
                data: {
                    name: npm,
                    npm: npm};                },
               success : function (friend) {
                    html = '<a class="list-group-item clearfix">' +
                            nama + ' (' + npm +')</a>';
                    $("#friend-list").append(html)
                },
                error : function (error) {
                    alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
                }
            });
        };

        $("#add-friend").on("submit", function (event) {
          alert("pressed");
          event.preventDefault();
            var npm = $("#field_npm").val();
            var corsProxy = 'https://cors-anywhere.herokuapp.com/';
            var obj = new Object(); obj.access_token = token; obj.client_id = cid;
            var param = $.param(obj);
            $.ajax({
                method: "GET",
                url: corsProxy+'https://api-dev.cs.ui.ac.id/siakngcs/mahasiswa/'+npm+'/?'+param,
                success: function(data) {
                    addFriend(data.nama, data.npm, data.alamat_mhs,data.kd_pos_mhs,
                              data.kota_lahir,data.tgl_lahir,
                              data.program[0].nm_org,data.program[0].nm_prg)
                },
                error: function(error) {
                    console.log(error)
                    alert("\n\t\t\tNPM tidak valid:\n\n'Tidak ada mahasiswa dengan NPM tersebut'")
                }
            });
            event.preventDefault();
        });

        $("#field_npm").change(function () {
            console.log( $(this).val() );
            npm = $(this).val();
            $.ajax({
                method: "POST",
                url: '{% url "lab-7:validate-npm" %}',
                data: {
                    'npm': npm
                },
                dataType: 'json',
                success: function (data) {
                    console.log(data)
                    if (data.is_taken) {
                        alert("Mahasiswa dengan npm seperti ini sudah ada");
                    }
                }
            });
        });
    </script>
{% endblock %}

lab_7/templates/lab_7/info.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
<section name="friend-list" class="friend-list">
    <div class="container">
        <div class="row">
        	<div class="col-md-8 col-lg-12">
        		<h2>{{ friend.friend_name }} </h2>
        	</div>
            <div class="col-md-8 col-lg-12">
                <table width="100%">
	                <tr>
	                	<td><h4>NPM</h4></td>
	                	<td><h4>{{ friend.npm }}</h4></td>
	                </tr>
	                <tr>
	                	<td><h4>Alamat</h4></td>
	                	<td><h4  id="address">{{ friend.address }}</h4></td>
	                </tr>
	                <tr>
	                	<td><h4>Kode Pos</h4>
	                	<td><h4>{{ friend.postcode }}</h4></td>
	                </tr>
	                <tr>
	                	<td><h4>Tempat Lahir</h4></td>
	                	<td><h4>{{ friend.hometown }}</h4></td>
                    </tr>
                    <tr>
	                	<td><h4>Tanggal Lahir</h4></td>
	                	<td><h4>{{ friend.birthday }}</h4></td>
                    </tr>
                    <tr>
	                	<td><h4>Program Studi</h4></td>
	                	<td><h4>{{ friend.course }}</h4></td>
                    </tr>
                    <tr>
	                	<td><h4>Angkatan</h4></td>
	                	<td><h4>{{ friend.batch }}</h4></td>
            		</tr>
            	</table>
            </div>
        </div>
    </div>
     <div class="container">
    	<div id="googleMap" style="width:1000px; height:300px; margin: 50px 0"></div>
    </div>
    <div>
    </div>
</section>
{% endblock %}
{% block javascript %}
<script>
	console.log($("#address").text());
	var address = $("#address").text();

	function initMap() {
		var geocoder = new google.maps.Geocoder();
		geocoder.geocode({'address': address}, function(results, status) {
			if (status === google.maps.GeocoderStatus.OK) {
				var propertiPeta = {
					center: results[0].geometry.location,
					zoom: 15,
					mapTypeId: google.maps.MapTypeId.ROADMAP
				};
				var peta = new google.maps.Map(document.getElementById("googleMap"), propertiPeta);
				var marker = new google.maps.Marker({
				  map: peta,
				  position: results[0].geometry.location
				});
			} else {
				var html = '<div class="alert alert-danger text-center">\
                            	Lokasi tidak ditemukan!\
                            </div>';
                $("#googleMap").append(html)
			}
		});
	}
</script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <div class="list-group">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix">
                                {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                <span class="pull-right">
                        <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}','{{ mahasiswa.alamat_mhs }}','{{ mahasiswa.kd_pos_mhs }}', '{{ mahasiswa.kota_lahir }}', '{{ mahasiswa.tgl_lahir }}', '{{ mahasiswa.program.0.nm_org}}', '{{ mahasiswa.program.0.angkatan}}')">
                            Tambah sebagai teman
                        </span>
                    </span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}
                    <div class="pagination">
                        <span class="step-links">
                            {% if mahasiswa_list.has_previous %}
                                <a href="?page={{ mahasiswa_list.previous_page_number }}">previous</a>
                            {% endif %}
                    
                            <span class="current">
                                Page {{ mahasiswa_list.number }} of {{ mahasiswa_list.paginator.num_pages }}.
                            </span>
                    
                            {% if mahasiswa_list.has_next %}
                                <a href="?page={{ mahasiswa_list.next_page_number }}">next</a>
                            {% endif %}
                        </span>
                        {% if auth %}
                            <div id="token" hidden="true">{{ auth.access_token }}</div>
                            <div id="cid" hidden="true">{{ auth.client_id }}</div>
                        {% endif %}
    
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">npm</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">name</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

{% block javascript %}
<script>

    var token = document.getElementById("token").innerHTML;
    var cid = document.getElementById("cid").innerHTML;

    var addFriend = function(nama,npm,address,postcode,hometown,birthday,course,batch) {
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:add-friend" %}',
            data: { 
                name: nama,
                npm: npm,
                address: address,
                postcode: postcode,
                hometown: hometown,
                birthday: birthday,
                course: course,
                batch: batch,
            },
           success : function (friend) {
                html = '<a class="list-group-item clearfix">' +
                        nama + ' (' + npm +')</a>';
                $("#friend-list").append(html)
            },
            error : function (error) {
                alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
            }
        });
    };

    $("#add-friend").on("submit", function (event) {
        var npm = $("#field_npm").val();
        var corsProxy = 'https://cors-anywhere.herokuapp.com/';
        var obj = new Object(); obj.access_token = token; obj.client_id = cid;
        var param = $.param(obj);
        $.ajax({
            method: "GET",
            url: corsProxy+'https://api-dev.cs.ui.ac.id/siakngcs/mahasiswa/'+npm+'/?'+param,
            success: function(data) {
                addFriend(data.nama, data.npm, data.alamat_mhs,data.kd_pos_mhs,
                          data.kota_lahir,data.tgl_lahir,
                          data.program[0].nm_org,data.program[0].nm_prg)
            },
            error: function(error) {
                console.log(error)
                alert("\n\t\t\tNPM tidak valid:\n\n'Tidak ada mahasiswa dengan NPM tersebut'")
            }
        });
        event.preventDefault();
    });

    $("#field_npm").change(function () {
        console.log( $(this).val() );
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm
            },
            dataType: 'json',
            success: function (data) {
                console.log(data)
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                }
            }
        });
    });
</script>
{% endblock %}